# Supabase Local & Production Project Configuration

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[auth]
enabled = true
site_url = "https://smart-bite-rosy.vercel.app"
additional_redirect_urls = ["https://smart-bite-rosy.vercel.app/reset-password", "https://smart-bite-rosy.vercel.app/verify"]
jwt_expiry = 3600
enable_signup = true

[auth.password]
# Prevent users from using known compromised passwords via HaveIBeenPwned API check
hibp_enabled = true
minimum_length = 8
required_characters = "lowercase,uppercase,digits"
